// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjsX1v35OGM4Fi9jdhe36bdhw3D3wptsE',
    appId: '1:779515567706:web:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '779515567706',
    projectId: 'localityconnector-ff384',
    authDomain: 'localityconnector-ff384.firebaseapp.com',
    storageBucket: 'localityconnector-ff384.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsX1v35OGM4Fi9jdhe36bdhw3D3wptsE',
    appId: '1:779515567706:android:320bbf367c74b985fdc263',
    messagingSenderId: '779515567706',
    projectId: 'localityconnector-ff384',
    storageBucket: 'localityconnector-ff384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsX1v35OGM4Fi9jdhe36bdhw3D3wptsE',
    appId: '1:779515567706:ios:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '779515567706',
    projectId: 'localityconnector-ff384',
    storageBucket: 'localityconnector-ff384.firebasestorage.app',
    iosClientId:
        '779515567706-llelel6ordlf54bcjbdbv22dsgpvr0p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.localityconnector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjsX1v35OGM4Fi9jdhe36bdhw3D3wptsE',
    appId: '1:779515567706:ios:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '779515567706',
    projectId: 'localityconnector-ff384',
    storageBucket: 'localityconnector-ff384.firebasestorage.app',
    iosClientId:
        '779515567706-llelel6ordlf54bcjbdbv22dsgpvr0p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.localityconnector',
  );
}
