name: localityconnector
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.0
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15  # For push notifications
  cloud_firestore: ^4.13.6    # Changed to cloud_firestore with correct version
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  path: any
  google_maps_flutter: ^2.5.3  # For Google Maps integration
  location: ^5.0.3  # For getting current user location
  geocoding: ^2.1.1  # For address/location conversion
  provider: ^6.1.1  # State management
  http: ^1.2.0  # For API calls
  # package_info_plus: ^8.3.0  # For getting app info and signing details
  shared_preferences: ^2.2.2  # For storing local preferences
  flutter_rating_bar: ^4.0.1  # For rating system
  cached_network_image: ^3.3.1  # For caching network images
  # flutter_local_notifications: ^15.1.0+1  # Temporarily removed due to compatibility issues
  geolocator: ^10.1.0  # Geolocation services
  google_generative_ai: ^0.2.2  # For Gemini API integration
  geoflutterfire2: ^2.3.15  # For geospatial queries with Firestore
  url_launcher: ^6.2.4  # For launching URLs like Google Maps
  flutter_tts: ^3.8.5  # For text-to-speech functionality in Jarvis
  avatar_glow: ^2.0.2  # For voice animation effect

dev_dependencies:
  flutter_test:
    sdk: flutter
    # flutter_native_splash: ^2.3.3
    # image: assets/images/land.png
    # color: "#000000"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/land.png
    - assets/images/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#0099FF"
    theme_color: "#0099FF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
